import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useRef } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const canvasRef = useRef(null)
  useEffect(() => {
    const canvas = canvasRef.current
    const context = canvas.getContext('2d')
    context.fillStyle = '#000000'
    context.fillRect(0, 0, context.canvas.width, context.canvas.height)
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.grid}>
          <img id="sample-video" src="http://localhost:9080/stream" />
        </div>
        <div className={styles.grid}>
          <canvas ref={canvasRef}></canvas>
        </div>
        <div>
          <button>Record</button>
          <button>Stop</button>
        </div>
        <div>
          <a href="#" id="download-link">Download</a>
        </div>
      </main>
    </>
  )
}
