version: '3.8'
services:
  editor:
    image: whoatemyapplepie/mjpeg-editor:0.9.0
    build:
      context: ./editor
      args:
        - GO_VERSION=${GO_VERSION}
        - GO_BUILDER_OS=${GO_BUILDER_OS}
        - GO_BUILDER_ARCH=${GO_BUILDER_ARCH}
        - NODE_VERSION=${NODE_VERSION}
        - NODE_BUILDER_OS=${NODE_BUILDER_OS}
        - NODE_BUILDER_ARCH=${NODE_BUILDER_ARCH}
    ports:
      - 4000:3000
      - 4090:3090
    volumes:
      - ../:/project
    working_dir: /project
    tty: true